### ISSUE TITLE
Are LDAP login failures / configuration problems logged somewhere?

### ISSUE THREAD

**Issue by snelson2013** [sonyxperiadev/BacklogTool#146]
I am having trouble getting the LDAP authentication working.  I have an ldap server (openldap) and have successfully used it with .Net webapps but do not seem to be able to get it to work with Backlog Tool.  

Is there anywhere that I can find some sort of logging information about that process in order to help troubleshoot what is wrong?  I assume it is something in my config but I think it should work.

**Comment by fredriklindman** [comment]
We have a similar issue here:
https://github.com/sonyxperiadev/BacklogTool/issues/4

See if it makes any difference when modify the file /main/webapp/WEB-INF/spring/spring-security.xml according to Geralds solution there. If it does help, we will update BacklogTool with that solution since several users have reported the issue.

The exceptions thrown should be visible somewhere in the Tomcat logs, I will come back with more details tomorrow.

**Comment by fredriklindman** [comment]
You should be able to find the logs under ${CATALINA_BASE}/logs. On Linux this would most likely be /usr/share/tomcat7/logs/

**Comment by snelson2013** [comment]
I got this working a few weeks ago and really like the tool!  The problem was in my configuration and I am putting a template of what I got working just in case it helps others.

`# LDAP server settings:
ldap.url=ldap://openldap.mycompany.com:389/dc=dev,dc=mycompany,dc=com
ldap.managerdn=uid=backlogtool,ou=People,dc=dev,dc=mycompany,dc=com
ldap.managerpassword=password
ldap.user-search-filter=(uid={0})
ldap.user-search-base=ou=People`
