### ISSUE TITLE
Add save button on each story next to the cancel button

### ISSUE THREAD

**Issue by fredriklindman** [sonyxperiadev/BacklogTool#21]
Users don't like when there's a cancel button, but not a save button on each story that has been edited. Add a save button next to cancel.

**Comment by nilsi** [comment]
I think we need some inputs on this one.

We discussed this today and this is what we came up with.

<b>Add individual save button on each story, disable multi editing</b>
Add a save button to every story, but allow only one story to be open in edit mode at a time. This is a very quick fix.

<b>Add individual save button on each story, multi editing enabled</b>
Add a save button to every story. Also allow editing of several stories at the same time. This is probably exactly what Gustaf wanted but would be very time consuming to code.

<b>Save all button on every story</b>
Have it like now but simply duplicate the save all button and move them to every story next to the cancel button.
So when the save all button is pressed on one story, all stories would be saved and also exiting edit mode (due to rebuilding). Super quick fix.

<b>Remove the cancel button</b>
Removing the cancel button and only have one save all button at the top which saves all stories in edit mode. You exit edit mode with the escape key. I don't like this one.

<b>Autosaving</b>
On keystroke, put a timer to 2 seconds and reset it on a new keystroke, save when the timer goes out. This would take a little bit longer than <b>"Add individual save button on each story, multi editing enabled"</b> to implement I guess but it could also be really nice.

**Comment by GLundh** [comment]
I think it could prove to be problematic if the user could not edit two stories at the same time. I for one would like to copy stuff between stories. Could you give a rough estimate for developing "Add individual save button on each story, multi editing enabled"?

**Comment by sublibra** [comment]
I agree with Gustaf but are also interested in how you think about the autosaving functionality. I would prefer this but with an undo functionality. How hard is the autosave plus undo?

**Comment by GLundh** [comment]
Autosave worries me. If I delete a story text by accident, I certainly do not want backlog tool to autosave 2 seconds later :/ Perhaps if the autosave function just saves the text as a retrievable draft somewhere it could work...

**Comment by nilsi** [comment]
I say it would take around 4-7 days of work for one person. But it could be really awesome. There is an built in undo functionality in current browsers for textareas and input fields. We could also extend this maybe if its needed.

**Comment by GLundh** [comment]
I think we should start work against "Add individual save button on each story, multi editing enabled" and Andreas seems to agree. If we notice that the feature will drag out, I guess we'll have to re-evaluate the necessity of the feature.

But I think it will be hard to give a decent estimate until we have really seen some real focus on this feature. So I say: let's start and we'll take a look at the progress sometime next week. I think this feature is important enough to warrant some extra dev time. Does that sounds OK with you all?

I also like auto-save, and I think we should work towards an autosave function which don't necessarily overwrites the current story-text. I would like to see more ideas/use-cases regarding this..

**Comment by nilsi** [comment]
Sounds good to me, we start working on  "Add individual save button on each story, multi editing enabled" while having auto-save back in our mind. Me and Fredrik will probably take a Skype meeting about this and discuss more precisely what needs to be done.

**Comment by sublibra** [comment]
Sounds good. Gustaf and I almost agree :). An undo would be interesting in any case but I agree with your way forward.
