### ISSUE TITLE
README.md mentions to download war-file, but no link

### ISSUE THREAD

**Issue by frazor** [sonyxperiadev/BacklogTool#61]
"For users

```
Download the backlogtool.war backlogtool.properties files from Github to a suitable location"
```

But there's no link to a war-file anywhere on the page (at least not that I'm able to spot).

Wanted: Please update readme with a link to the war-file for convenient download.

Thank you!

**Comment by fredriklindman** [comment]
Thank you for your report!
We are about to host the binaries somewhere else since GitHub has removed the "downloads" page as you correctly pointed out. The link will be updated asap.

**Comment by frazor** [comment]
Excellent, thank you! Is there anywhere I can get it in the meantime? Or is the binary simply not available at the moment then?

**Comment by fredriklindman** [comment]
A very temporary solution...

http://www61.zippyshare.com/v/47275086/file.html

**Comment by frazor** [comment]
Gracias Señor, perfect!

**Comment by frazor** [comment]
Can I extract an example backlogtool.properties from the war somehow?

**Comment by fredriklindman** [comment]
You're welcome!
Oh I forgot that part. The properties file is unfortunately not embedded in the war file. Ask Gustaf if you need it now, otherwise I can send it tonight.

--- Originalmeddelande ---

Från: "Luthander" notifications@github.com
Skickat: 4 juni 2013 13:51
Till: "sonyxperiadev/BacklogTool" BacklogTool@noreply.github.com
Kopia: "Fredrik Persson" fredrik-persson@outlook.com
Ämne: Re: [BacklogTool] README.md mentions to download war-file, but no link (#61)

Can I extract an example backlogtool.properties from the war somehow?

---

**Comment by frazor** [comment]
It's ok, I found it in the git of course..

https://github.com/sonyxperiadev/BacklogTool/blob/master/backlogtool.properties

Thanks for the help. Closing. :-)
